"""
test_report_cache.py — estate-view read-only contract in build_segments.

The shared document-estate view (SHARED_REPORTS_DIR/<slug>) is regenerated by a
separate builder process; this pipeline must treat it as strictly read-only.
_report_cache may *select* it as a reuse source, but downloads/parses always
target the writable REPORTS_DIR/<slug>.
"""
from __future__ import annotations

from scripts import build_segments as bs


def _wire(monkeypatch, tmp_path):
    shared_root = tmp_path / "estate" / "views" / "reports"
    reports_root = tmp_path / "data" / "reports"
    monkeypatch.setattr(bs, "SHARED_REPORTS_DIR", shared_root)
    monkeypatch.setattr(bs, "REPORTS_DIR", reports_root)
    return shared_root, reports_root


def test_view_with_md_is_selected(monkeypatch, tmp_path):
    shared, reports = _wire(monkeypatch, tmp_path)
    view = shared / "acme"
    view.mkdir(parents=True)
    (view / "2024-1T.md").write_text("x", encoding="utf-8")

    assert bs._report_cache("acme") == view


def test_view_without_md_falls_back_to_writable(monkeypatch, tmp_path):
    shared, reports = _wire(monkeypatch, tmp_path)
    view = shared / "acme"
    view.mkdir(parents=True)          # exists but empty (e.g. only xbrl/ symlinks)

    assert bs._report_cache("acme") == reports / "acme"


def test_missing_view_falls_back_to_writable(monkeypatch, tmp_path):
    _, reports = _wire(monkeypatch, tmp_path)
    assert bs._report_cache("acme") == reports / "acme"


def test_force_download_bypasses_view(monkeypatch, tmp_path):
    shared, reports = _wire(monkeypatch, tmp_path)
    view = shared / "acme"
    view.mkdir(parents=True)
    (view / "2024-1T.md").write_text("x", encoding="utf-8")

    assert bs._report_cache("acme", force_download=True) == reports / "acme"
