company:
  currency: MXN
  exchange: ''
  language: es
  name: New Company
  ticker: ''
  unit: thousands
custom_metrics: []
ir_website:
  url: https://grupoherdez.com.mx/investors-financial-information#reports
metric_overrides: {}
