"""sys.path setup so scripts can import both earnlib.* and the vendored
alpha-go src.* package.

alpha-go's modules import each other as ``from src.download... import ...``,
so vendor/alpha-go must be on sys.path and the name ``src`` is taken — which
is why this project's package is called ``earnlib``.
"""
from __future__ import annotations

import subprocess
import sys
import hashlib
from pathlib import Path

EARNINGS_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = EARNINGS_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.append(str(REPO_ROOT))
from estate_bridge import load_estate_bridge  # noqa: E402

ESTATE_BRIDGE = load_estate_bridge(project_root=REPO_ROOT)

# Self-contained since 2026-07-28: the used subsets of the former sibling
# trees now live inside earnings/. data/soft mirrors soft/'s layout
# (data/reports facts+mdna, configs, outputs/_reconcile, .cache/market_data);
# vendor/alpha-go carries the imported src package plus the frozen catalog
# inputs (xbrl_concepts.yaml, archive_index.html, documents.db).
ALPHA_GO_ROOT = EARNINGS_ROOT / "vendor" / "alpha-go"
SOFT_ROOT = EARNINGS_ROOT / "data" / "soft"

# Copies of the monorepo-root historical-extraction inputs used by
# build_metrics_hist / build_events_hist (outputs/ metrics CSVs, the
# per-company pdf-md report texts, and the extraction config yamls).
LEGACY_OUTPUTS_DIR = EARNINGS_ROOT / "data" / "legacy_outputs"
LEGACY_REPORTS_DIR = EARNINGS_ROOT / "data" / "legacy_reports"
LEGACY_CONFIGS_DIR = EARNINGS_ROOT / "data" / "legacy_configs"

CONFIG_PATH = EARNINGS_ROOT / "configs" / "study.yaml"
SNAPSHOT_DIR = EARNINGS_ROOT / "data" / "snapshots" / "market_data"
OUTPUTS_DIR = EARNINGS_ROOT / "outputs"

# Audit-v2 switch: EARNINGS_V2=1 routes versioned artifacts to *_v2 files and
# result tables to results_v2/, so the original frozen outputs are never
# overwritten. Unset (default) reproduces the pre-audit pipeline exactly.
#
# Audit-v3 switch: EARNINGS_V3=1 is the shared-infra + timing re-baselining.
# It implies the v2 corrections and additionally (a) resolves the ``src``
# package to the MONOREPO ROOT extraction engine instead of the vendored
# alpha-go copy, (b) reads XBRL facts from the shared document estate view
# instead of the data/soft mirror, and (c) routes the artifacts it regenerates
# to *_v3 files / results_v3 so v2 and original outputs stay frozen.
import os

V3 = os.environ.get("EARNINGS_V3") == "1"
V2 = V3 or os.environ.get("EARNINGS_V2") == "1"
RESULTS_DIR = OUTPUTS_DIR / ("results_v3" if V3 else "results_v2" if V2 else "results")

# Integration mode for the estate (the single place the decision lives).
# "direct" reads the read-only symlink view in the monorepo; "synced" would
# read a local snapshot under data/estate/reports refreshed by a sync script
# (vendor_sync pattern) — intentionally a stub until such a script exists.
ESTATE_MODE = os.environ.get("EARNINGS_ESTATE_MODE", "direct")
ESTATE_VIEW_DIR = (
    EARNINGS_ROOT / "data" / "estate" / "reports"
    if ESTATE_MODE == "synced"
    else ESTATE_BRIDGE.reports_view_dir
)

# artifacts regenerated by the v2 audit; everything else keeps one name
_V2_ARTIFACTS = {"metrics_hist", "prices", "surprises", "event_windows"}
# artifacts regenerated by the v3 re-baselining. v2-only stems keep their _v2
# files under V3: prices (snapshot inputs untouched) and metrics_hist (the
# historical PDF-tier re-extraction through the root engine is a DEFERRED
# workstream — v3 inherits the certified _v2 history; build_metrics_hist
# refuses to run under V3).
_V3_ARTIFACTS = {"metrics", "events", "events_hist", "events_all",
                 "event_windows", "kpi_panel", "surprises", "universe"}


def art_path(stem: str, ext: str = ".parquet") -> Path:
    if V3 and stem in _V3_ARTIFACTS:
        return OUTPUTS_DIR / f"{stem}_v3{ext}"
    if V2 and stem in _V2_ARTIFACTS:
        return OUTPUTS_DIR / f"{stem}_v2{ext}"
    return OUTPUTS_DIR / f"{stem}{ext}"


_VINTAGE: set[tuple[str, str]] | None = None


def facts_vintage() -> set[tuple[str, str]]:
    """Frozen (slug, period) facts universe for the dev sample (v3 reads).

    Pinned by scripts/pin_facts_vintage.py from the certified artifacts; keeps
    post-freeze XBRL backfills and new filings out of development rebuilds.
    """
    global _VINTAGE
    if _VINTAGE is None:
        path = EARNINGS_ROOT / "configs" / "facts_vintage.csv"
        if not path.exists():
            raise FileNotFoundError(
                "configs/facts_vintage.csv missing — run scripts/pin_facts_vintage.py"
            )
        import csv

        with open(path) as fh:
            _VINTAGE = {(r["slug"], r["period"]) for r in csv.DictReader(fh)}
    return _VINTAGE


import re as _re

# Canonical root view names normally use <TICKER>_<PERIOD>_facts.json.  An
# immutable collision-safe route can insert one or two discriminators before
# the period; historical views can instead append a project suffix after
# "_facts".  The period nearest the terminal facts marker is authoritative.
_FACTS_NAME_RE = _re.compile(
    r"_(?P<period>\d{4}-(?:[1-4]T|FY))_facts(?:__[^.]*)?\.json$"
)


def facts_period(path: Path, ticker: str) -> str | None:
    """Period label from a facts filename (view or mirror naming)."""
    if not path.name.startswith(f"{ticker}_"):
        return None
    m = _FACTS_NAME_RE.search(path.name)
    if m:
        return m.group("period")
    return None


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _canonical_root_facts(
    company: str | None = None,
) -> dict[tuple[str, str], Path]:
    """Catalog-authorized canonical facts, keyed by (company, period).

    V3 treats the estate catalog—not a symlink target or a copied Soft tree—as
    the source of truth.  Hashes are retained so a stale or colliding report
    view entry cannot be mistaken for the root-owned derivative.
    """
    from src.shared.document_estate import EstateReader

    if not ESTATE_BRIDGE.catalog_path.is_file():
        return {}
    with EstateReader(ESTATE_BRIDGE.catalog_path) as reader:
        companies = (
            (reader.resolve_company(company),)
            if company is not None
            else tuple(reader.companies())
        )
        out: dict[tuple[str, str], Path] = {}
        for canonical in companies:
            refs = reader.artifacts(
                canonical,
                project="root",
                role="xbrl_facts",
                fmt="json",
            )
            hashes = {ref.path: ref.sha256 for ref in refs}
            current = reader.xbrl_facts_map(
                canonical,
                project="root",
                role="xbrl_facts",
            )
            for period, path in current.items():
                expected_hash = hashes.get(path)
                if (
                    expected_hash is not None
                    and path.is_file()
                    and _file_sha256(path) == expected_hash
                ):
                    out[(canonical, period)] = path
        return out


def _estate_root_facts(slug: str, ticker: str) -> dict[str, Path]:
    """period -> verified root-owned canonical facts for one issuer."""
    out: dict[str, Path] = {}
    for (company, period), path in _canonical_root_facts(slug).items():
        if company == slug and facts_period(path, ticker) == period:
            out[period] = path
    return out


def facts_glob(slug: str, ticker: str) -> list[Path]:
    """Quarterly ``*_facts.json`` files for one company.

    v3: root-owned canonical derivatives from the shared estate, verified
    against catalog role and hash, AND the frozen facts vintage.  Default:
    the historical frozen data/soft mirror.
    """
    if V3:
        vintage = facts_vintage()
        by_period = _estate_root_facts(slug, ticker)
        return [by_period[k] for k in sorted(by_period)
                if (slug, k) in vintage]
    return sorted((SOFT_ROOT / "data" / "reports" / slug / "xbrl")
                  .glob(f"{ticker}_*_facts.json"))


def facts_exists(slug: str, ticker: str, period: str) -> bool:
    """Whether facts for one (company, period) are available."""
    if V3:
        if (slug, period) not in facts_vintage():
            return False
        return period in _estate_root_facts(slug, ticker)
    return (SOFT_ROOT / "data" / "reports" / slug / "xbrl"
            / f"{ticker}_{period}_facts.json").exists()


def facts_root_glob(pattern: str = "*/xbrl/*_facts.json") -> list[Path]:
    """All facts files across companies under the active mode."""
    if V3:
        vintage = facts_vintage()
        return sorted(
            path
            for key, path in _canonical_root_facts().items()
            if key in vintage
        )
    return sorted((SOFT_ROOT / "data" / "reports").glob(pattern))


# Engine selection: the package name ``src`` is claimed process-wide by
# whichever tree is first on sys.path — vendored alpha-go by default, the
# monorepo root engine under V3. Never mix both engines in one process.
_SRC_ROOT = REPO_ROOT if V3 else ALPHA_GO_ROOT

for _p in (str(EARNINGS_ROOT), str(_SRC_ROOT)):
    if _p not in sys.path:
        sys.path.insert(0, _p)


def load_config() -> dict:
    import yaml

    with open(CONFIG_PATH) as fh:
        return yaml.safe_load(fh)


def load_universe(cfg: dict, which: str = "full") -> dict:
    """slug -> {ticker, symbol}. 'phase_a' = the explicit study.yaml block;
    'full' = the frozen auto-resolved configs/universe_full.yaml (109 slugs)."""
    if which == "phase_a":
        return cfg["universe"]
    import yaml

    path = EARNINGS_ROOT / "configs" / "universe_full.yaml"
    with open(path) as fh:
        return yaml.safe_load(fh)["universe"]


def repo_head(repo: Path = REPO_ROOT) -> str:
    """Git HEAD of the monorepo, recorded as provenance in outputs."""
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"
