"""sys.path setup so scripts can import both earnlib.* and the vendored
alpha-go src.* package.

alpha-go's modules import each other as ``from src.download... import ...``,
so vendor/alpha-go must be on sys.path and the name ``src`` is taken — which
is why this project's package is called ``earnlib``.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

EARNINGS_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = EARNINGS_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.append(str(REPO_ROOT))
from estate_bridge import load_estate_bridge  # noqa: E402

ESTATE_BRIDGE = load_estate_bridge(project_root=REPO_ROOT)

# Self-contained since 2026-07-28: the used subsets of the former sibling
# trees now live inside earnings/. data/soft mirrors soft/'s layout
# (data/reports facts+mdna, configs, outputs/_reconcile, .cache/market_data);
# vendor/alpha-go carries the imported src package plus the frozen catalog
# inputs (xbrl_concepts.yaml, archive_index.html, documents.db).
ALPHA_GO_ROOT = EARNINGS_ROOT / "vendor" / "alpha-go"
SOFT_ROOT = EARNINGS_ROOT / "data" / "soft"

# Copies of the monorepo-root historical-extraction inputs used by
# build_metrics_hist / build_events_hist (outputs/ metrics CSVs, the
# per-company pdf-md report texts, and the extraction config yamls).
LEGACY_OUTPUTS_DIR = EARNINGS_ROOT / "data" / "legacy_outputs"
LEGACY_REPORTS_DIR = EARNINGS_ROOT / "data" / "legacy_reports"
LEGACY_CONFIGS_DIR = EARNINGS_ROOT / "data" / "legacy_configs"

CONFIG_PATH = EARNINGS_ROOT / "configs" / "study.yaml"
SNAPSHOT_DIR = EARNINGS_ROOT / "data" / "snapshots" / "market_data"
OUTPUTS_DIR = EARNINGS_ROOT / "outputs"

# Audit-v2 switch: EARNINGS_V2=1 routes versioned artifacts to *_v2 files and
# result tables to results_v2/, so the original frozen outputs are never
# overwritten. Unset (default) reproduces the pre-audit pipeline exactly.
#
# Audit-v3 switch: EARNINGS_V3=1 is the shared-infra + timing re-baselining.
# It implies the v2 corrections and additionally (a) resolves the ``src``
# package to the MONOREPO ROOT extraction engine instead of the vendored
# alpha-go copy, (b) reads XBRL facts from the shared document estate view
# instead of the data/soft mirror, and (c) routes the artifacts it regenerates
# to *_v3 files / results_v3 so v2 and original outputs stay frozen.
import os

V3 = os.environ.get("EARNINGS_V3") == "1"
V2 = V3 or os.environ.get("EARNINGS_V2") == "1"
RESULTS_DIR = OUTPUTS_DIR / ("results_v3" if V3 else "results_v2" if V2 else "results")

# Integration mode for the estate (the single place the decision lives).
# "direct" reads the read-only symlink view in the monorepo; "synced" would
# read a local snapshot under data/estate/reports refreshed by a sync script
# (vendor_sync pattern) — intentionally a stub until such a script exists.
ESTATE_MODE = os.environ.get("EARNINGS_ESTATE_MODE", "direct")
ESTATE_VIEW_DIR = (
    EARNINGS_ROOT / "data" / "estate" / "reports"
    if ESTATE_MODE == "synced"
    else ESTATE_BRIDGE.reports_view_dir
)

# artifacts regenerated by the v2 audit; everything else keeps one name
_V2_ARTIFACTS = {"metrics_hist", "prices", "surprises", "event_windows"}
# artifacts regenerated by the v3 re-baselining. v2-only stems keep their _v2
# files under V3: prices (snapshot inputs untouched) and metrics_hist (the
# historical PDF-tier re-extraction through the root engine is a DEFERRED
# workstream — v3 inherits the certified _v2 history; build_metrics_hist
# refuses to run under V3).
_V3_ARTIFACTS = {"metrics", "events", "events_hist", "events_all",
                 "event_windows", "kpi_panel", "surprises", "universe"}


def art_path(stem: str, ext: str = ".parquet") -> Path:
    if V3 and stem in _V3_ARTIFACTS:
        return OUTPUTS_DIR / f"{stem}_v3{ext}"
    if V2 and stem in _V2_ARTIFACTS:
        return OUTPUTS_DIR / f"{stem}_v2{ext}"
    return OUTPUTS_DIR / f"{stem}{ext}"


_VINTAGE: set[tuple[str, str]] | None = None


def facts_vintage() -> set[tuple[str, str]]:
    """Frozen (slug, period) facts universe for the dev sample (v3 reads).

    Pinned by scripts/pin_facts_vintage.py from the certified artifacts; keeps
    post-freeze soft additions (xbrl backfill, new filings) out of dev rebuilds.
    """
    global _VINTAGE
    if _VINTAGE is None:
        path = EARNINGS_ROOT / "configs" / "facts_vintage.csv"
        if not path.exists():
            raise FileNotFoundError(
                "configs/facts_vintage.csv missing — run scripts/pin_facts_vintage.py"
            )
        import csv

        with open(path) as fh:
            _VINTAGE = {(r["slug"], r["period"]) for r in csv.DictReader(fh)}
    return _VINTAGE


def _is_soft_facts(p: Path) -> bool:
    """True when an estate-view symlink resolves to soft's facts tree.

    The view holds every project's artifacts: soft facts under the soft slug
    dirs, ROOT-engine facts under root slug dirs (plain-named there — the
    ``__root`` suffix only marks same-directory collisions). The study's facts
    universe is soft's, so estate reads must filter by symlink target, not name.
    """
    try:
        target = p.resolve()
    except OSError:
        return False
    return "/soft/data/reports/" in str(target)


import re as _re

# view names: <TICKER>_<PERIOD>_facts.json, plus per-project collision variants
# <TICKER>_<PERIOD>_facts__soft.json / _facts__root.json (whichever project
# linked second gets suffixed, per directory). Period extraction must therefore
# parse up to "_facts", never slice a fixed suffix.
_FACTS_NAME_RE = _re.compile(r"^(?P<ticker>.+?)_(?P<period>\d{4}-(?:[1-4]T|FY))_facts")


def facts_period(path: Path, ticker: str) -> str | None:
    """Period label from a facts filename (view or mirror naming)."""
    m = _FACTS_NAME_RE.match(path.name)
    if m and m.group("ticker") == ticker:
        return m.group("period")
    return None


def _estate_soft_facts(d: Path, ticker: str) -> dict[str, Path]:
    """period -> soft-project facts symlink in one estate view xbrl dir.

    Selects by symlink TARGET (soft's tree), never by name: the plain name may
    belong to either project depending on import order, with the loser suffixed
    ``__soft``/``__root``. Stale " 2"-suffixed duplicates are skipped.
    """
    out: dict[str, Path] = {}
    for p in d.glob(f"{ticker}_*_facts*.json"):
        if " " in p.name or not _is_soft_facts(p):
            continue
        period = facts_period(p, ticker)
        if period is None:
            continue
        # prefer the plain name when several soft-target links exist
        if period not in out or len(p.name) < len(out[period].name):
            out[period] = p
    return out


def facts_glob(slug: str, ticker: str) -> list[Path]:
    """Quarterly ``*_facts.json`` files for one company (soft project's facts).

    v3: the shared estate view filtered to soft-project targets AND the frozen
    facts vintage; default: the frozen data/soft mirror (which can itself drift
    — the vintage pin is what keeps v3 reproducible).
    """
    if V3:
        vintage = facts_vintage()
        by_period = _estate_soft_facts(ESTATE_VIEW_DIR / slug / "xbrl", ticker)
        return [by_period[k] for k in sorted(by_period)
                if (slug, k) in vintage or k.endswith("-FY")]
    return sorted((SOFT_ROOT / "data" / "reports" / slug / "xbrl")
                  .glob(f"{ticker}_*_facts.json"))


def facts_exists(slug: str, ticker: str, period: str) -> bool:
    """Whether the soft facts file for one (company, period) is available."""
    if V3:
        if (slug, period) not in facts_vintage():
            return False
        d = ESTATE_VIEW_DIR / slug / "xbrl"
        return any(
            _is_soft_facts(p) and " " not in p.name
            for p in d.glob(f"{ticker}_{period}_facts*.json")
        )
    return (SOFT_ROOT / "data" / "reports" / slug / "xbrl"
            / f"{ticker}_{period}_facts.json").exists()


def facts_root_glob(pattern: str = "*/xbrl/*_facts.json") -> list[Path]:
    """All soft facts files across companies under the active mode."""
    if V3:
        vintage = facts_vintage()
        seen = []
        for p in ESTATE_VIEW_DIR.glob("*/xbrl/*_facts*.json"):
            if " " in p.name or not _FACTS_NAME_RE.match(p.name):
                continue
            m = _FACTS_NAME_RE.match(p.name)
            slug = p.parents[1].name
            if (slug, m.group("period")) not in vintage:
                continue
            if _is_soft_facts(p):
                seen.append(p)
        return sorted(seen)
    return sorted((SOFT_ROOT / "data" / "reports").glob(pattern))


# Engine selection: the package name ``src`` is claimed process-wide by
# whichever tree is first on sys.path — vendored alpha-go by default, the
# monorepo root engine under V3. Never mix both engines in one process.
_SRC_ROOT = REPO_ROOT if V3 else ALPHA_GO_ROOT

for _p in (str(EARNINGS_ROOT), str(_SRC_ROOT)):
    if _p not in sys.path:
        sys.path.insert(0, _p)


def load_config() -> dict:
    import yaml

    with open(CONFIG_PATH) as fh:
        return yaml.safe_load(fh)


def load_universe(cfg: dict, which: str = "full") -> dict:
    """slug -> {ticker, symbol}. 'phase_a' = the explicit study.yaml block;
    'full' = the frozen auto-resolved configs/universe_full.yaml (109 slugs)."""
    if which == "phase_a":
        return cfg["universe"]
    import yaml

    path = EARNINGS_ROOT / "configs" / "universe_full.yaml"
    with open(path) as fh:
        return yaml.safe_load(fh)["universe"]


def repo_head(repo: Path = REPO_ROOT) -> str:
    """Git HEAD of the monorepo, recorded as provenance in outputs."""
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"
